#pragma once
#include <Windows.h>

enum CallRequests
{
	TEST_CALL				  = CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1488, METHOD_BUFFERED, FILE_SPECIAL_ACCESS),
	BSOD_CALL				  = CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1489, METHOD_BUFFERED, FILE_SPECIAL_ACCESS),
	READ_VIRTUAL_MEMORY_CALL  = CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1490, METHOD_BUFFERED, FILE_SPECIAL_ACCESS),
	WRITE_VIRTUAL_MEMORY_CALL = CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1491, METHOD_BUFFERED, FILE_SPECIAL_ACCESS),
	GET_CLIENTDLL_ADDR		  = CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1492, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
};